name: Check yaml structure
on:
    push:
        branches:
            - "hotfix/**"
    pull_request:
        branches:
            - main
jobs:
    Checking-yaml-structure:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install yaml lint
              run: |
               sudo apt-get update
               sudo apt-get install yamllint 
            - name: run yamllint
              run: |
                yamllint -d "{extends: default, rule: {spaces: 4}}"  .